/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/Airports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    query?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AirportLookupResponse"];
                        "application/json": components["schemas"]["AirportLookupResponse"];
                        "text/json": components["schemas"]["AirportLookupResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SearchRequest"];
                    "text/json": components["schemas"]["SearchRequest"];
                    "application/*+json": components["schemas"]["SearchRequest"];
                };
            };
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SearchSessionResponse"];
                        "application/json": components["schemas"]["SearchSessionResponse"];
                        "text/json": components["schemas"]["SearchSessionResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Search/{searchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Direct?: boolean;
                    OneStop?: boolean;
                    TwoPlusStop?: boolean;
                    Providers?: string;
                    Airlines?: string;
                    DepartureAirports?: string;
                    ArrivalAirports?: string;
                    MaxDuration?: number;
                    DepartureTime?: string;
                    ArrivalTime?: string;
                    Page?: number;
                    PageSize?: number;
                    HasStopFilter?: boolean;
                    IsPaginationRequested?: boolean;
                };
                header?: never;
                path: {
                    searchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SearchSessionResponse"];
                        "application/json": components["schemas"]["SearchSessionResponse"];
                        "text/json": components["schemas"]["SearchSessionResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AirportLookupResponse: {
            airports?: components["schemas"]["AirportOption"][] | null;
        };
        AirportOption: {
            code?: string | null;
            name?: string | null;
            displayLabel?: string | null;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        SearchFilterOptionCount: {
            value?: string | null;
            /** Format: int32 */
            count?: number;
        };
        SearchFiltersMetadata: {
            providers?: components["schemas"]["SearchFilterOptionCount"][] | null;
            airlines?: components["schemas"]["SearchFilterOptionCount"][] | null;
            departureAirports?: components["schemas"]["SearchFilterOptionCount"][] | null;
            arrivalAirports?: components["schemas"]["SearchFilterOptionCount"][] | null;
            durationMinutes?: components["schemas"]["SearchRangeMetadata"];
            departureTimeMinutes?: components["schemas"]["SearchRangeMetadata"];
            arrivalTimeMinutes?: components["schemas"]["SearchRangeMetadata"];
            stops?: components["schemas"]["SearchStopFilterMetadata"];
        };
        SearchMetadata: {
            /** Format: int32 */
            searchCombinationCount?: number;
            /** Format: int32 */
            providerResultCount?: number;
            /** Format: int32 */
            returnedResultCount?: number;
            /** Format: int32 */
            returnedDirectFlightCount?: number;
            /** Format: int32 */
            returnedOneStopFlightCount?: number;
            /** Format: int32 */
            returnedTwoPlusStopFlightCount?: number;
        };
        SearchPagination: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            totalResults?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        SearchRangeMetadata: {
            /** Format: int32 */
            min?: number;
            /** Format: int32 */
            max?: number;
        };
        SearchRequest: {
            originAirports?: string[] | null;
            destinationAirports?: string[] | null;
            selectedDates?: string[] | null;
            /** Format: date */
            returnDateFrom?: string | null;
            /** Format: date */
            returnDateTo?: string | null;
            /** Format: int32 */
            adults?: number;
            cabinClass?: string | null;
        };
        SearchResponse: {
            results?: components["schemas"]["SearchResult"][] | null;
            metadata?: components["schemas"]["SearchMetadata"];
            filters?: components["schemas"]["SearchFiltersMetadata"];
            pagination?: components["schemas"]["SearchPagination"];
        };
        SearchResult: {
            id?: string | null;
            isRoundTrip?: boolean;
            legs?: components["schemas"]["SearchResultLeg"][] | null;
            /** Format: int32 */
            totalDurationMinutes?: number;
            priceOptions?: components["schemas"]["SearchResultPriceOption"][] | null;
        };
        SearchResultLeg: {
            originAirport?: string | null;
            destinationAirport?: string | null;
            /** Format: date-time */
            departureLocalTime?: string;
            /** Format: date-time */
            arrivalLocalTime?: string;
            /** Format: int32 */
            durationMinutes?: number;
            segments?: components["schemas"]["SearchResultSegment"][] | null;
        };
        SearchResultPrice: {
            /** Format: double */
            amount?: number;
            currency?: string | null;
        };
        SearchResultPriceOption: {
            id?: string | null;
            provider?: string | null;
            totalPrice?: components["schemas"]["SearchResultPrice"];
            deepLink?: string | null;
        };
        SearchResultSegment: {
            marketingCarrierName?: string | null;
            marketingCarrierCode?: string | null;
            flightNumber?: string | null;
            originAirport?: string | null;
            destinationAirport?: string | null;
            /** Format: date-time */
            departureLocalTime?: string;
            /** Format: date-time */
            arrivalLocalTime?: string;
            /** Format: int32 */
            durationMinutes?: number;
        };
        SearchSessionResponse: {
            searchId?: string | null;
            status?: string | null;
            /** Format: int32 */
            totalCombinations?: number;
            /** Format: int32 */
            completedCombinations?: number;
            /** Format: int32 */
            failedCombinations?: number;
            response?: components["schemas"]["SearchResponse"];
            errorMessage?: string | null;
        };
        SearchStopFilterMetadata: {
            /** Format: int32 */
            direct?: number;
            /** Format: int32 */
            oneStop?: number;
            /** Format: int32 */
            twoPlusStop?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
