/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/Airports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    query?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AirportLookupResponse"];
                        "application/json": components["schemas"]["AirportLookupResponse"];
                        "text/json": components["schemas"]["AirportLookupResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/Search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SearchRequest"];
                    "text/json": components["schemas"]["SearchRequest"];
                    "application/*+json": components["schemas"]["SearchRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SearchResponse"];
                        "application/json": components["schemas"]["SearchResponse"];
                        "text/json": components["schemas"]["SearchResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AirportLookupResponse: {
            airports?: components["schemas"]["AirportOption"][] | null;
        };
        AirportOption: {
            code?: string | null;
            name?: string | null;
            displayLabel?: string | null;
        };
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        } & {
            [key: string]: unknown;
        };
        SearchMetadata: {
            /** Format: int32 */
            searchCombinationCount?: number;
            /** Format: int32 */
            providerResultCount?: number;
            /** Format: int32 */
            returnedResultCount?: number;
            /** Format: int32 */
            returnedDirectFlightCount?: number;
            /** Format: int32 */
            returnedOneStopFlightCount?: number;
            /** Format: int32 */
            returnedTwoPlusStopFlightCount?: number;
        };
        SearchRequest: {
            originAirports?: string[] | null;
            destinationAirports?: string[] | null;
            /** Format: date */
            departDateFrom?: string;
            /** Format: date */
            departDateTo?: string;
            /** Format: date */
            returnDateFrom?: string | null;
            /** Format: date */
            returnDateTo?: string | null;
            /** Format: int32 */
            adults?: number;
            cabinClass?: string | null;
        };
        SearchResponse: {
            results?: components["schemas"]["SearchResult"][] | null;
            metadata?: components["schemas"]["SearchMetadata"];
        };
        SearchResult: {
            id?: string | null;
            isRoundTrip?: boolean;
            legs?: components["schemas"]["SearchResultLeg"][] | null;
            /** Format: int32 */
            totalDurationMinutes?: number;
            priceOptions?: components["schemas"]["SearchResultPriceOption"][] | null;
        };
        SearchResultLeg: {
            originAirport?: string | null;
            destinationAirport?: string | null;
            /** Format: date-time */
            departureUtc?: string;
            /** Format: date-time */
            arrivalUtc?: string;
            /** Format: int32 */
            durationMinutes?: number;
            segments?: components["schemas"]["SearchResultSegment"][] | null;
        };
        SearchResultPrice: {
            /** Format: double */
            amount?: number;
            currency?: string | null;
        };
        SearchResultPriceOption: {
            id?: string | null;
            provider?: string | null;
            totalPrice?: components["schemas"]["SearchResultPrice"];
            deepLink?: string | null;
        };
        SearchResultSegment: {
            marketingCarrierName?: string | null;
            marketingCarrierCode?: string | null;
            flightNumber?: string | null;
            originAirport?: string | null;
            destinationAirport?: string | null;
            /** Format: date-time */
            departureUtc?: string;
            /** Format: date-time */
            arrivalUtc?: string;
            /** Format: int32 */
            durationMinutes?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
